//
//  HelperForms.swift
//  CiudadInvisible
//
//  Created by Mathias Carignani on 19/07/14.
//  Copyright (c) 2014 Ciudad Invisible. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

class HelperForms : NSObject {

    //// Cache

    struct Cache {
        static var imageOfFlecha: UIImage!
        static var flechaTargets: [AnyObject]!
    }

    //// Initialization

    override class func load() {
    }

    //// Drawing Methods

    class func drawFlecha() {

        //// Bezier 2 Drawing
        var bezier2Path = UIBezierPath()
        bezier2Path.moveToPoint(CGPointMake(0, 3))
        bezier2Path.addLineToPoint(CGPointMake(13, 11))
        bezier2Path.addLineToPoint(CGPointMake(26, 3))
        bezier2Path.addLineToPoint(CGPointMake(24, 1))
        bezier2Path.addLineToPoint(CGPointMake(13, 8))
        bezier2Path.addLineToPoint(CGPointMake(2, 1))
        bezier2Path.addLineToPoint(CGPointMake(0, 3))
        bezier2Path.closePath()
        UIColor.whiteColor().setFill()
        bezier2Path.fill()
        UIColor.blackColor().setStroke()
        bezier2Path.lineWidth = 0.5
        bezier2Path.stroke()
    }

    //// Generated Images

    class var imageOfFlecha: UIImage {
        if (Cache.imageOfFlecha) {
            return Cache.imageOfFlecha!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(26, 15), false, 0)
        HelperForms.drawFlecha()
        Cache.imageOfFlecha = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfFlecha!
    }

    //// Customization Infrastructure

    @IBOutlet var flechaTargets: [AnyObject] {
        get { return Cache.flechaTargets }
        set {
            Cache.flechaTargets = newValue
            for target: AnyObject in newValue {
                (target as StyleKitSettableImage).image = HelperForms.imageOfFlecha
            }
        }
    }

}

@objc protocol StyleKitSettableImage {
    var image: UIImage! { get set }
}

@objc protocol StyleKitSettableSelectedImage {
    var selectedImage: UIImage! { get set }
}
